"""Sidebar component for file loading and navigation."""

from pathlib import Path

import streamlit as st

from apps.transect_viewer import config
from apps.transect_viewer.utils.data_loader import load_npz, load_npz_from_upload, get_all_transect_ids
from apps.transect_viewer.utils.date_parser import infer_epoch_date, format_date_for_display


def render_sidebar() -> str:
    """
    Render the sidebar with file loading and view selection.

    Returns:
        Selected view mode string
    """
    st.sidebar.title("CliffCast Viewer")

    # File loading section
    st.sidebar.header("Data Loading")

    # Option 1: File uploader
    uploaded_file = st.sidebar.file_uploader(
        "Upload NPZ file",
        type=["npz"],
        help="Upload a transect NPZ file generated by extract_transects.py"
    )

    # Option 2: Path input
    st.sidebar.markdown("**Or enter file path:**")
    file_path = st.sidebar.text_input(
        "NPZ file path",
        value=config.DEFAULT_DATA_PATH,
        label_visibility="collapsed",
    )

    # Load button
    col1, col2 = st.sidebar.columns(2)

    with col1:
        if st.button("Load File", use_container_width=True):
            _load_from_path(file_path)

    with col2:
        if st.button("Clear Data", use_container_width=True):
            _clear_data()

    # Handle uploaded file
    if uploaded_file is not None:
        if st.session_state.current_file != uploaded_file.name:
            _load_from_upload(uploaded_file)

    # Show loaded data info
    _render_data_info()

    # View mode selection
    st.sidebar.header("View Mode")
    view_mode = st.sidebar.selectbox(
        "Select view",
        config.VIEW_MODES,
        label_visibility="collapsed",
    )

    # View-specific options
    _render_view_options(view_mode)

    return view_mode


def _load_from_path(file_path: str):
    """Load data from file path."""
    path = Path(file_path)

    if not path.exists():
        st.sidebar.error(f"File not found: {file_path}")
        return

    try:
        with st.spinner("Loading data..."):
            data = load_npz(str(path))
            st.session_state.data = data
            st.session_state.current_file = path.name

            # Set default transect ID
            transect_ids = get_all_transect_ids(data)
            if transect_ids:
                st.session_state.selected_transect_id = transect_ids[0]

            # Add to epochs dict
            epoch_date = infer_epoch_date(data.get('las_sources', []))
            if epoch_date:
                date_key = epoch_date.strftime('%Y-%m-%d')
            else:
                date_key = path.stem
            st.session_state.epochs[date_key] = data

        st.sidebar.success(f"Loaded: {path.name}")
    except Exception as e:
        st.sidebar.error(f"Error loading file: {e}")


def _load_from_upload(uploaded_file):
    """Load data from uploaded file."""
    try:
        with st.spinner("Loading uploaded file..."):
            data = load_npz_from_upload(uploaded_file)
            st.session_state.data = data
            st.session_state.current_file = uploaded_file.name

            # Set default transect ID
            transect_ids = get_all_transect_ids(data)
            if transect_ids:
                st.session_state.selected_transect_id = transect_ids[0]

            # Add to epochs dict
            epoch_date = infer_epoch_date(data.get('las_sources', []))
            if epoch_date:
                date_key = epoch_date.strftime('%Y-%m-%d')
            else:
                date_key = Path(uploaded_file.name).stem
            st.session_state.epochs[date_key] = data

        st.sidebar.success(f"Loaded: {uploaded_file.name}")
    except Exception as e:
        st.sidebar.error(f"Error loading file: {e}")


def _clear_data():
    """Clear all loaded data."""
    st.session_state.data = None
    st.session_state.epochs = {}
    st.session_state.selected_transect_id = None
    st.session_state.selected_transects = []
    st.session_state.current_file = None
    st.rerun()


def _render_data_info():
    """Render information about loaded data."""
    if st.session_state.data is None:
        st.sidebar.info("No data loaded")
        return

    data = st.session_state.data

    st.sidebar.markdown("---")
    st.sidebar.subheader("Loaded Data")

    # Basic stats
    n_transects = data['points'].shape[0]
    n_points = data['points'].shape[1]
    n_features = data['points'].shape[2]

    st.sidebar.metric("Transects", n_transects)
    st.sidebar.metric("Points/Transect", n_points)
    st.sidebar.metric("Features", n_features)

    # Epoch date
    epoch_date = infer_epoch_date(data.get('las_sources', []))
    st.sidebar.metric("Epoch Date", format_date_for_display(epoch_date))

    # Loaded epochs
    if len(st.session_state.epochs) > 1:
        st.sidebar.markdown(f"**Epochs loaded:** {len(st.session_state.epochs)}")
        for date_key in sorted(st.session_state.epochs.keys()):
            st.sidebar.text(f"  - {date_key}")


def _render_view_options(view_mode: str):
    """Render view-specific options in sidebar."""
    if st.session_state.data is None:
        return

    st.sidebar.markdown("---")
    st.sidebar.subheader("View Options")

    data = st.session_state.data

    if view_mode == "Single Transect Inspector":
        # Transect selector
        transect_ids = get_all_transect_ids(data)

        selected_id = st.sidebar.selectbox(
            "Transect ID",
            transect_ids,
            index=transect_ids.index(st.session_state.selected_transect_id)
            if st.session_state.selected_transect_id in transect_ids
            else 0,
        )
        st.session_state.selected_transect_id = selected_id

        # Feature selector
        feature_names = data.get('feature_names', [])
        if isinstance(feature_names, list) and feature_names:
            selected_feature = st.sidebar.selectbox(
                "Primary Feature",
                feature_names,
                index=feature_names.index(st.session_state.selected_feature)
                if st.session_state.selected_feature in feature_names
                else 0,
            )
            st.session_state.selected_feature = selected_feature

    elif view_mode == "Transect Evolution":
        # Multi-file loading for evolution view
        st.sidebar.markdown("**Load additional epochs:**")
        additional_file = st.sidebar.file_uploader(
            "Add epoch",
            type=["npz"],
            key="evolution_uploader",
        )
        if additional_file is not None:
            _load_additional_epoch(additional_file)

    elif view_mode == "Cross-Transect View":
        # Metadata field selector for map coloring
        metadata_names = data.get('metadata_names', [])
        if isinstance(metadata_names, list) and metadata_names:
            st.sidebar.selectbox(
                "Color map by",
                metadata_names,
                index=0,
                key="map_color_field",
            )


def _load_additional_epoch(uploaded_file):
    """Load additional epoch file."""
    file_key = uploaded_file.name

    # Check if already loaded
    for date_key in st.session_state.epochs:
        if file_key in date_key or date_key in file_key:
            return

    try:
        data = load_npz_from_upload(uploaded_file)

        # Add to epochs dict
        epoch_date = infer_epoch_date(data.get('las_sources', []))
        if epoch_date:
            date_key = epoch_date.strftime('%Y-%m-%d')
        else:
            date_key = Path(uploaded_file.name).stem

        if date_key not in st.session_state.epochs:
            st.session_state.epochs[date_key] = data
            st.sidebar.success(f"Added epoch: {date_key}")

    except Exception as e:
        st.sidebar.error(f"Error loading epoch: {e}")
